language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:migrate
script:
  - bundle exec rake test
